- name: install apache on ubuntu server
  tags: apache,ubuntu
  ansible.builtin.apt:
    name:
      - "{{ apache_package }}"
  when: ansible_distribution == "Ubuntu"

- name: install apache on fedora server
  tags: apache,fedora
  ansible.builtin.dnf:
    name:
      - "{{ apache_package }}"
    use_backend: dnf
  when: ansible_distribution == "Fedora"

- name: Show package manager
  tags: test
  debug:
    msg: "Ansible thinks this system uses: {{ ansible_pkg_mgr }}"

- name: ensure apache is running 
  tags: apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started

- name: update apache site
  tags: apache,ubuntu
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: change server admin email
  tags: apache,fedora
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin hamil@gmail.com
  when: ansible_distribution == "Fedora"
  notify: restart_apache